package pojos;
// Generated Aug 30, 2017 5:21:25 AM by Hibernate Tools 4.3.1



/**
 * LaptopModel generated by hbm2java
 */
public class LaptopModel  implements java.io.Serializable {


     private Integer laptopModelId;
     private String laptopModelLaptopId;
     private String laptopModelHardDisk;
     private String laptopModelRam;
     private String laptopModelVga;
     private String laptopModelProcessor;
     private String laptopModelUsbType1;
     private String laptopModelUsbType2;
     private String laptopModelHdmi;
     private String laptopModelVgaOutput;
     private String laptopModelScreenSize;
     private Integer laptopModelCacheMemory;
     private Integer laptopModelStatus;
     private String laptopModelImagePath;

    public LaptopModel() {
    }

    public LaptopModel(String laptopModelLaptopId, String laptopModelHardDisk, String laptopModelRam, String laptopModelVga, String laptopModelProcessor, String laptopModelUsbType1, String laptopModelUsbType2, String laptopModelHdmi, String laptopModelVgaOutput, String laptopModelScreenSize, Integer laptopModelCacheMemory, Integer laptopModelStatus, String laptopModelImagePath) {
       this.laptopModelLaptopId = laptopModelLaptopId;
       this.laptopModelHardDisk = laptopModelHardDisk;
       this.laptopModelRam = laptopModelRam;
       this.laptopModelVga = laptopModelVga;
       this.laptopModelProcessor = laptopModelProcessor;
       this.laptopModelUsbType1 = laptopModelUsbType1;
       this.laptopModelUsbType2 = laptopModelUsbType2;
       this.laptopModelHdmi = laptopModelHdmi;
       this.laptopModelVgaOutput = laptopModelVgaOutput;
       this.laptopModelScreenSize = laptopModelScreenSize;
       this.laptopModelCacheMemory = laptopModelCacheMemory;
       this.laptopModelStatus = laptopModelStatus;
       this.laptopModelImagePath = laptopModelImagePath;
    }
   
    public Integer getLaptopModelId() {
        return this.laptopModelId;
    }
    
    public void setLaptopModelId(Integer laptopModelId) {
        this.laptopModelId = laptopModelId;
    }
    public String getLaptopModelLaptopId() {
        return this.laptopModelLaptopId;
    }
    
    public void setLaptopModelLaptopId(String laptopModelLaptopId) {
        this.laptopModelLaptopId = laptopModelLaptopId;
    }
    public String getLaptopModelHardDisk() {
        return this.laptopModelHardDisk;
    }
    
    public void setLaptopModelHardDisk(String laptopModelHardDisk) {
        this.laptopModelHardDisk = laptopModelHardDisk;
    }
    public String getLaptopModelRam() {
        return this.laptopModelRam;
    }
    
    public void setLaptopModelRam(String laptopModelRam) {
        this.laptopModelRam = laptopModelRam;
    }
    public String getLaptopModelVga() {
        return this.laptopModelVga;
    }
    
    public void setLaptopModelVga(String laptopModelVga) {
        this.laptopModelVga = laptopModelVga;
    }
    public String getLaptopModelProcessor() {
        return this.laptopModelProcessor;
    }
    
    public void setLaptopModelProcessor(String laptopModelProcessor) {
        this.laptopModelProcessor = laptopModelProcessor;
    }
    public String getLaptopModelUsbType1() {
        return this.laptopModelUsbType1;
    }
    
    public void setLaptopModelUsbType1(String laptopModelUsbType1) {
        this.laptopModelUsbType1 = laptopModelUsbType1;
    }
    public String getLaptopModelUsbType2() {
        return this.laptopModelUsbType2;
    }
    
    public void setLaptopModelUsbType2(String laptopModelUsbType2) {
        this.laptopModelUsbType2 = laptopModelUsbType2;
    }
    public String getLaptopModelHdmi() {
        return this.laptopModelHdmi;
    }
    
    public void setLaptopModelHdmi(String laptopModelHdmi) {
        this.laptopModelHdmi = laptopModelHdmi;
    }
    public String getLaptopModelVgaOutput() {
        return this.laptopModelVgaOutput;
    }
    
    public void setLaptopModelVgaOutput(String laptopModelVgaOutput) {
        this.laptopModelVgaOutput = laptopModelVgaOutput;
    }
    public String getLaptopModelScreenSize() {
        return this.laptopModelScreenSize;
    }
    
    public void setLaptopModelScreenSize(String laptopModelScreenSize) {
        this.laptopModelScreenSize = laptopModelScreenSize;
    }
    public Integer getLaptopModelCacheMemory() {
        return this.laptopModelCacheMemory;
    }
    
    public void setLaptopModelCacheMemory(Integer laptopModelCacheMemory) {
        this.laptopModelCacheMemory = laptopModelCacheMemory;
    }
    public Integer getLaptopModelStatus() {
        return this.laptopModelStatus;
    }
    
    public void setLaptopModelStatus(Integer laptopModelStatus) {
        this.laptopModelStatus = laptopModelStatus;
    }
    public String getLaptopModelImagePath() {
        return this.laptopModelImagePath;
    }
    
    public void setLaptopModelImagePath(String laptopModelImagePath) {
        this.laptopModelImagePath = laptopModelImagePath;
    }




}


